# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/finall with comments/finall with comments/nano_processor.cache/wt} [current_project]
set_property parent.project_path {D:/finall with comments/finall with comments/nano_processor.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo {d:/finall with comments/finall with comments/nano_processor.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/Add_Sub_Unit.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/CLA_Adder.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/Decoder_3_to_8.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/Decorder_2_to_4.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/FA.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/HA.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/Instruction_Decoder.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/LUT_16_7.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/Mux_2W_4B.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/Mux_8W_4B.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/Mux_8_to_1.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/PC.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/ROM.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/Reg_bank.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/Slow_Clk.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/register4.vhd}
  {D:/finall with comments/finall with comments/nano_processor.srcs/sources_1/new/NanoProcessor.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/finall with comments/finall with comments/nano_processor.srcs/constrs_1/imports/finall with comments/Basys3Labs1.xdc}}
set_property used_in_implementation false [get_files {{D:/finall with comments/finall with comments/nano_processor.srcs/constrs_1/imports/finall with comments/Basys3Labs1.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top NanoProcessor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NanoProcessor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file NanoProcessor_utilization_synth.rpt -pb NanoProcessor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
